version: "3"
services:
  giraffe-test-api:
    image: giraffe-test-api
    ports:
      - 5000:80
    environment:
      - POSTGRES_PORT=5433
      - POSTGRES_HOST=host.docker.internal

  giraffe-test-db:
    image: giraffe-test-db
    ports:
      - 5433:5432
    environment:
      - POSTGRES_PASSWORD=postgres
